require_relative "./movies_near_you/version"
require_relative "./movies_near_you/cli"
require_relative "./movies_near_you/movie"
require_relative "./movies_near_you/director"
require_relative "./movies_near_you/rating"
